HackneyRepairs/Services/HackneyWorkOrdersService.cs
HackneyRepairs/Tests/Services/HackneyWorkOrdersServiceTest.cs

There were cases where we were displaying a work order from the Data Warehouse, but it's status had changed today. This updates two service functions to retrieve all work orders which are not considered "terminal" (i.e. cannot change) from the Live database instead.

Fix stale work order status bug

---

HackneyRepairs/Services/HackneyWorkOrdersService.cs

Handles `retrievedWarehouseWorkOrders` being `null`.

Fix null UHW work orders error

---

HackneyRepairs/Builders/ResponseBuilder.cs
HackneyRepairs/Controllers/AppointmentsController.cs
HackneyRepairs/Controllers/NotesController.cs
HackneyRepairs/Controllers/PropertiesController.cs
HackneyRepairs/Controllers/RepairsController.cs
HackneyRepairs/Controllers/WorkOrdersController.cs
HackneyRepairs/HackneyRepairs.csproj
HackneyRepairs/Models/ApiErrorMessage.cs
HackneyRepairs/Tests/Integration/WorkOrdersIntegrationTest.cs

The responses in the workorders controller have been refactored with a response builder class

refactor controller responses in workorders controller

---

HackneyRepairs/Fact/WhenUniversalHousingIsRunningAttribute.cs
HackneyRepairs/Tests/Repository/UHWWarehouseRepositoryTest.cs
HackneyRepairs/Tests/Repository/UhtRepositoryTest.cs
HackneyRepairs/Tests/Services/HackneyWorkOrdersServiceTest.cs
HackneyRepairs/Tests/UniversalHousingSimulator.cs
README.md

Extracted from the previous PR. Needed some changes since the behaviour of the repositories has been reverted.

REBASE - Add Universal Housing repository tests

---

HackneyRepairs/Repository/DRSRepository.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Repository/UhtRepository.cs
HackneyRepairs/Repository/UhwRepository.cs

Using Dapper + parametised queries

Resolve sql injection vulnerability

---

HackneyRepairs/Builders/ResponseBuilder.cs
HackneyRepairs/Controllers/AppointmentsController.cs
HackneyRepairs/Controllers/NotesController.cs
HackneyRepairs/Controllers/PropertiesController.cs
HackneyRepairs/Controllers/RepairsController.cs
HackneyRepairs/Tests/Integration/PropertiesIntegrationTests.cs
HackneyRepairs/Validators/ScheduleBookingRequestValidator.cs

Refactor controller responses using the ResponseBuilder class

Refactoring controllers

---

HackneyRepairs/HackneyRepairs.csproj
HackneyRepairs/NLog.config

**what**
View a stream of logs from the application

Configure centralised logging to Papertrail

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Repository/UhtRepository.cs

Replace the field where the address is grabbed from the db

Replace the field where the address is retrieved from the db

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Controllers/PropertiesController.cs
HackneyRepairs/Interfaces/IHackneyPropertyService.cs
HackneyRepairs/Interfaces/IUHWWarehouseRepository.cs
HackneyRepairs/Models/PropertyDetails.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/FakePropertyService.cs
HackneyRepairs/Services/HackneyPropertyService.cs
HackneyRepairs/Tests/Actions/PropertyActionsTest.cs
HackneyRepairs/Tests/Integration/PropertiesIntegrationTests.cs

The response of this and the get property by reference endpoint has also been extended with two extra attributes

Get properties by multiple references endpoint implemented

---

HackneyRepairs/NLog.config
HackneyRepairs/Startup.cs

Configure Swagger documentation to accept an authentication token

---

HackneyRepairs/Actions/NoteActions.cs
HackneyRepairs/Interfaces/IHackneyNotesService.cs
HackneyRepairs/Interfaces/IHackneyWorkOrdersService.cs
HackneyRepairs/Interfaces/IUhtRepository.cs
HackneyRepairs/Interfaces/IUhwRepository.cs
HackneyRepairs/Models/NoteRequest.cs
HackneyRepairs/Repository/UhtRepository.cs
HackneyRepairs/Repository/UhwRepository.cs
HackneyRepairs/Services/FakeNotesService.cs
HackneyRepairs/Services/FakeWorkOrdersService.cs
HackneyRepairs/Services/HackneyNotesService.cs
HackneyRepairs/Services/HackneyWorkOrdersService.cs
HackneyRepairs/Tests/Actions/NotesActionTests.cs

The stored procedure used for adding notes in UH was not found under the same name in UH Live. I have adapted the code to use a second stored procedure shared between the two environments.

Fix issue when calling the stored procedure due an inconsistency between dev uh and live uh 

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Controllers/PropertiesController.cs
HackneyRepairs/Interfaces/IHackneyPropertyService.cs
HackneyRepairs/Interfaces/IUHWWarehouseRepository.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/FakePropertyService.cs
HackneyRepairs/Services/HackneyPropertyService.cs
HackneyRepairs/Tests/Actions/PropertyActionsTest.cs

Number of records returned limited to value of limit parameter

Add limit to parameter

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Controllers/PropertiesController.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/HackneyPropertyService.cs

update search parameter in query

search fix

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs

Non numbered address now returned

fix for returning address

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/FakePropertyService.cs
HackneyRepairs/Tests/Actions/PropertyActionsTest.cs
HackneyRepairs/Tests/Integration/PropertiesIntegrationTests.cs

This endpoint will now be returning a tenure for a property, we made changes to the tests and a section of the SQL.

Extending property search endpoint 

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Models/PropertyDetails.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/FakePropertyService.cs
HackneyRepairs/Tests/Actions/PropertyActionsTest.cs
HackneyRepairs/Tests/Integration/PropertiesIntegrationTests.cs

Extended the property search by ref endpoint to provide a tenure code.

Property search tenure extension minor

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs

property by ref query

---

HackneyRepairs/Actions/PropertyActions.cs
HackneyRepairs/Controllers/RepairsController.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Services/FakePropertyService.cs
HackneyRepairs/Tests/Actions/PropertyActionsTest.cs
HackneyRepairs/Tests/Integration/PropertiesIntegrationTests.cs
HackneyRepairs/Validators/RepairRequestValidator.cs

Added back tenure code for properties, implemented extended sorcode validation in repairrequestvalidator class as requested.

tenure code, invalid sorcode

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Validators/RepairRequestValidator.cs

Faciliities query improved and sorcode developer error updated to indicate that sorcode is prohibited

improved facilities filter query

---

HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Controllers/CautionaryContactController.cs
HackneyRepairs/Factories/HackneyCautionaryContactServiceFactory.cs
HackneyRepairs/Interfaces/IUhtRepository.cs
HackneyRepairs/Interfaces/IUhwRepository.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Repository/UhtRepository.cs
HackneyRepairs/Repository/UhwRepository.cs
HackneyRepairs/Services/HackneyCautionaryContactService.cs
HackneyRepairs/Services/HackneyKeyFaxServiceRequestBuilder.cs
HackneyRepairs/Tests/Repository/UhtRepositoryTest.cs
HackneyRepairs/Tests/Repository/UhwRepositoryTests.cs

Update to cautionary contacts reponse object
And keyfax request

Fix for cautionary contacts

---

HackneyRepairs/Repository/UhtRepository.cs

Changed field to retrieve property area/neighbourhood

Update to get-property query

---

.gitignore
HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Controllers/KeyFaxController.cs
HackneyRepairs/HackneyRepairs.csproj
HackneyRepairs/Interfaces/IHackneyKeyFaxServiceRequestBuilder.cs
HackneyRepairs/Properties/launchSettings.json
HackneyRepairs/Services/HackneyKeyFaxServiceRequestBuilder.cs
HackneyRepairs/Startup.cs
HackneyRepairs/Tests/Services/HackneyKeyfaxServiceRequestBuilderTests.cs

Parameterising the KeyFax integration

Keyfaxintegration

---

HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Controllers/KeyFaxController.cs
HackneyRepairs/Interfaces/IHackneyKeyFaxServiceRequestBuilder.cs
HackneyRepairs/Services/HackneyKeyFaxServiceRequestBuilder.cs
HackneyRepairs/Tests/Services/HackneyKeyfaxServiceRequestBuilderTests.cs

Added parameter for return url to keyfax start up endpoint

Return URL parameter

---

HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Controllers/KeyFaxController.cs
HackneyRepairs/Models/HackneyKeyfaxDataResponse.cs
HackneyRepairs/Models/KeyfaxData.cs

Returns FaultText, RepairCode, RepairCode Description and Priority

Parsed keyfax results

---

HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Controllers/KeyFaxController.cs
HackneyRepairs/Models/HackneyKeyfaxDataResponse.cs
HackneyRepairs/Models/KeyfaxData.cs

Updated API to handle keyfax webservice errors

Process alternate keyfax responses

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs

Search results do not require search terms to be in order.

removed requirement for order of search terms

---

HackneyRepairs/Actions/KeyFaxActions.cs
HackneyRepairs/Models/HackneyKeyfaxDataResponse.cs
HackneyRepairs/Models/KeyfaxData.cs

Changed fields  to string or object to allow flexible deserialization

keyfax XML deserialize

---

.gitignore
HackneyRepairs/Actions/RepairsActions.cs
HackneyRepairs/Controllers/RepairsController.cs

Add user friendly  error messages for creatiing repair request

Add error messages

---

HackneyRepairs/Actions/RepairsActions.cs
HackneyRepairs/Controllers/RepairsController.cs
HackneyRepairs/Controllers/WorkOrdersController.cs

[HttpPost("{workOrderReference}/issue")]
Read JSON request with email property.
Cheanged endpoint url

Changed endpoint to post

---

HackneyRepairs/Actions/NoteActions.cs
HackneyRepairs/Actions/RepairsActions.cs
HackneyRepairs/Controllers/WorkOrdersController.cs
HackneyRepairs/Interfaces/IHackneyRepairsService.cs
HackneyRepairs/Services/FakeRepairsService.cs
HackneyRepairs/Services/HackneyRepairsService.cs

Added endpoint for cancelling a work order.
Added some better messaging on the errors.

Added endpoint to cancel repair

---

HackneyRepairs/Models/RepairRequestOrder.cs
HackneyRepairs/Services/HackneyRepairsServiceRequestBuilder.cs

Enabled estimated units for multiple SORs

Updated create repair request for multiple SORs

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Repository/UhtRepository.cs

Please check i'm not breaking stuff and check the PR :)
Cheers!

Added trims to SQL request

---

HackneyRepairs/Models/UHWorkOrderBase.cs
HackneyRepairs/Repository/UHWWarehouseRepository.cs
HackneyRepairs/Repository/UhtRepository.cs

Retrieve 'authorised by' field for a work order

Display who authorised a work order

---

HackneyRepairs/Controllers/NotesController.cs
HackneyRepairs/Controllers/WorkOrdersController.cs
HackneyRepairs/Validators/NoteRequestValidator.cs

Updated to specified error messages

cancel workorder error messages

---

HackneyRepairs/Models/RepairRequest.cs
HackneyRepairs/Services/HackneyRepairsServiceRequestBuilder.cs

Creates a RECHARGE task if there isn't one present and the RECHARGE value is true

Add recharge task to a repair request

---

HackneyRepairs/Repository/UhwRepository.cs

Updated query to show alert for Duncan

Updated cautionary contact query

---

HackneyRepairs/Models/RepairRequestOrder.cs

Make estimated units nullable decimal

---

HackneyRepairs/Repository/UhwRepository.cs

UH test is now a viable environment.
needed to change the selector for the cross database queries in UHwRepository file

Added option for test UH in the UhwRepository file.

---

HackneyRepairs/Repository/UHWWarehouseRepository.cs

Amended to exclude test calls from datawarehouse .

Staging API was pulling from datawarehouse when it shouldn't

---

HackneyRepairs/Controllers/AppointmentsController.cs
HackneyRepairs/Repository/DRSRepository.cs
HackneyRepairs/Repository/UhtRepository.cs

Capture error message from DRS in drs exception class

User friendly error messages for errors captured in the API

---

HackneyRepairs/Repository/UhwRepository.cs

keys used to retrieve alerts, stored across 2 different views.
Previous query only used 'uprn' keys from properttyview view

updated query retrieving cautionary alerts

---

HackneyRepairs/Controllers/KeyFaxController.cs

"get_startup_url" endpoint 500 userMessage update

updated keyfax controller endpoint exception response

---

HackneyRepairs/Actions/NoteActions.cs
HackneyRepairs/Controllers/NotesController.cs

notes feed  endpoint 500 usermessage update
add note endpoint 500 usermessage update

Update  notes controller endpoint exception response

---

HackneyRepairs/Controllers/PropertiesController.cs

404 and 505 API response messages updated.
Removed redundant using statements.

Update properties controller endpoint exception response

---

HackneyRepairs/Actions/CautionaryContactActions.cs
HackneyRepairs/Controllers/CautionaryContactController.cs
HackneyRepairs/Models/CautionaryContactLevelModel.cs
HackneyRepairs/Repository/UhwRepository.cs
HackneyRepairs/Services/FakeCautionaryContactService.cs
HackneyRepairs/Tests/Actions/CautionaryContactActionsTests.cs

Endpoint query updated. 500 exception error message updated. Endpoint tests updated.
Error handling updated.
Removed redundant using statements.

Update cautionary alerts end point

---

HackneyRepairs/Controllers/WorkOrdersController.cs

404 and 505 API response messages updated.

Update work orders controller endpoint exception response

---

HackneyRepairs/Actions/CautionaryContactActions.cs
HackneyRepairs/Models/CautionaryContactLevelModel.cs
HackneyRepairs/Repository/UhwRepository.cs
HackneyRepairs/Services/FakeCautionaryContactService.cs
HackneyRepairs/Tests/Actions/CautionaryContactActionsTests.cs

Notes object contains relevant notes data.
Updated query to retrieve data about notes.
Updated endpoint tests

created notes object

---

HackneyRepairs/Actions/AppointmentActions.cs

Pushed error messages in to thrown exceptions

Added messages to thrown exceptions so we get some useful information when problems happen

---

HackneyRepairs/Actions/CacheActions.cs
HackneyRepairs/Builders/ResponseBuilder.cs
HackneyRepairs/Controllers/AppointmentsController.cs
HackneyRepairs/Controllers/CacheController.cs
HackneyRepairs/Extension/ServiceConfiguration.cs
HackneyRepairs/Factories/HackneyAppointmentServiceFactory.cs
HackneyRepairs/Factories/HackneyCacheServiceFactory .cs
HackneyRepairs/HackneyRepairs.csproj
HackneyRepairs/Infrastructure/CacheManager.cs
HackneyRepairs/Interfaces/ICacheRepository.cs
HackneyRepairs/Interfaces/ICacheService.cs
HackneyRepairs/Repository/CacheRepository.cs
HackneyRepairs/Repository/DRSRepository.cs
HackneyRepairs/Services/CacheService.cs
HackneyRepairs/Services/FakeCacheService.cs
HackneyRepairs/Services/HackneyAppointmentsService.cs
HackneyRepairs/Startup.cs
HackneyRepairs/Tests/Actions/CacheActionsTest.cs
HackneyRepairs/Tests/Integration/AppointmentsIntegrationTests.cs
HackneyRepairs/Utils/DRSCacheHelper.cs

Added caching to the appointments functionality.

Feature add redis

---

HackneyRepairs/Services/HackneyAppointmentsService.cs
HackneyRepairs/Startup.cs

Amended methods to deal with uht multiple appointments as well

---

HackneyRepairs/Services/HackneyAppointmentsService.cs

Refactor GetLatestAppointmentByWorkOrderReference to use new method which sets the source system for a appointment to Cached

Refactor GetLatestAppointmentByWorkOrderReference

---

HackneyRepairs/Services/HackneyAppointmentsService.cs

Update SetSourceSystem method to return a new list

Update SetSourceSystem method

---

HackneyRepairs/Actions/AppointmentActions.cs
HackneyRepairs/appsettings.json

Attempting to debug issue with dates from DRS

Added some logging and amended log level
